version: "3.9"
services:
  postgres:
    image: postgres:14.1-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_APP_DATABASE: "realjobs"
      POSTGRES_APP_USER: "realjobs"
      POSTGRES_APP_PASSWORD: "realjobs"
      INCLUDE_TEST_DATABASE: ${INCLUDE_TEST_DATABASE}
    volumes:
      - ./docker/pg-init-scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M