package world.inetum.realdolmen.realjobs.entities.enums;

public enum FunctionCategory {
    GENERAL_MANAGEMENT,
    EDUCATION_AND_TRAINING,
    LAW,
    RESEARCH_AND_DEVELOPMENT,
    HEALTH_MEDICINE_SOCIAL_AND_FITNESS,
    ACCOMMODATION_CATERING_AND_TOURISM,
    LAND_SEA_ENVIRONMENT_AND_VETERINARY,
    PUBLIC_SERVICES,
    POLICE_SECURITY_AND_PROTECTIVE,
    MEDIA_AND_INFORMATION,
    IT_AND_TELECOMMUNICATIONS,
    SALES_AND_PURCHASING,
    BANKING_FINANCE_SERVICES_AND_INSURANCE,
    FINANCE_ADMINISTRATION_AND_AUDITING,
    HR,
    MARKETING_AND_ADVERTISING,
    ADMINISTRATIVE_SUPPORT_AND_SECRETARIAL,
    TRANSPORT_AND_LOGISTICS,
    MANUFACTURING_BUILDING_AND_MANUAL_WORK,
    CULTURE_AND_FINE_ARTS,
    ENGINEERING_AND_TECHNICAL_JOBS,
    DESIGN_AND_ARCHITECTURE
}
