package world.inetum.realdolmen.realjobs.entities.enums;

public enum Industry {
    AEROSPACE, TRANSPORT, COMPUTER, TELECOMMUNICATION, AGRICULTURE, CONSTRUCTION, EDUCATION, PHARMACEUTICAL, FOOD, HEALTHCARE, HOSPITALITY, ENTERTAINMENT, NEWS_AND_MEDIA, ENERGY, MANUFACTURING, MUSIC, MINING, WORLD_WIDE_WEB, ELECTRONICS
}
