export enum Industry {
  AEROSPACE = "AEROSPACE",
  TRANSPORT = "TRANSPORT",
  COMPUTER = "COMPUTER",
  TELECOMMUNICATION = "TELECOMMUNICATION",
  AGRICULTURE = "AGRICULTURE",
  CONSTRUCTION = "CONSTRUCTION",
  EDUCATION = "EDUCATION",
  PHARMACEUTICAL = "PHARMACEUTICAL",
  FOOD = "FOOD",
  HEALTHCARE = "HEALTHCARE",
  HOSPITALITY = "HOSPITALITY",
  ENTERTAINMENT = "ENTERTAINMENT",
  NEWS_AND_MEDIA = "NEWS_AND_MEDIA",
  ENERGY = "ENERGY",
  MANUFACTURING = "MANUFACTURING",
  MUSIC = "MUSIC",
  MINING = "MINING",
  WORLD_WIDE_WEB = "WORLD_WIDE_WEB",
  ELECTRONICS = "ELECTRONICS"
}

export const INDUSTRY_OPTIONS = [
  {name: "Aerospace Industry", value: Industry.AEROSPACE},
  {name: "Transport Industry", value: Industry.TRANSPORT},
  {name: "Computer Industry", value: Industry.COMPUTER},
  {name: "Telecommunication industry", value: Industry.TELECOMMUNICATION},
  {name: "Agriculture industry", value: Industry.AGRICULTURE},
  {name: "Construction Industry", value: Industry.CONSTRUCTION},
  {name: "Education Industry", value: Industry.EDUCATION},
  {name: "Pharmaceutical Industry", value: Industry.PHARMACEUTICAL},
  {name: "Food Industry", value: Industry.FOOD},
  {name: "Health care Industry", value: Industry.HEALTHCARE},
  {name: "Hospitality Industry", value: Industry.HOSPITALITY},
  {name: "Entertainment Industry", value: Industry.ENTERTAINMENT},
  {name: "News Media Industry", value: Industry.NEWS_AND_MEDIA},
  {name: "Energy Industry", value: Industry.ENERGY},
  {name: "Manufacturing Industry", value: Industry.MANUFACTURING},
  {name: "Music Industry", value: Industry.MUSIC},
  {name: "Mining Industry", value: Industry.MINING},
  {name: "Worldwide web", value: Industry.WORLD_WIDE_WEB},
  {name: "Electronics Industry", value: Industry.ELECTRONICS},
];
